### PR TITLE
New modern design

### PR DESCRIPTION
**Pull request by Scalpel78**
Redesigned using Bootstrap. Not tested against database.

### CODE REVIEW

**Comment by Scalpel78** [comment]
It should look something like this:
image

**Comment by haavares** [comment]
Ser bra ut!

**Comment by jenschr** [comment]
Jepp! Go for it!

**Comment by aalemayhu** [comment]
@Scalpel78 Cool, but  it would be nice if the input divs where wrapped in their own `<div class="form-group"></div>`, to create some vertical space between them, currently they seem too close IMO.

**Comment by Scalpel78** [comment]
Allright, I'll add some more air to it.

**Pull request merged**
